"""
Django settings for findwine project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '****'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'catalog.apps.CatalogConfig',
    'wine.apps.WineConfig',
    'api.apps.APIConfig',
    'content.apps.ContentConfig',
    'integrations.apps.IntegrationsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'raven.contrib.django.raven_compat',
    'geoposition',
    'rest_framework',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'findwine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'wine.context_processors.site_meta',
            ],
        },
    },
]

WSGI_APPLICATION = 'findwine.wsgi.application'

# Fixtures location
FIXTURE_DIRS = (
    '/fixtures/',
)


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# use localsettings to override this
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


AWS_ACCESS_KEY_ID = '***'  # override with localsettings
AWS_SECRET_ACCESS_KEY = '***'  # override with localsettings
AWS_STORAGE_BUCKET_NAME = 'findwines3a'
AWS_QUERYSTRING_AUTH = False  # This will make sure that the file URL does not have unnecessary parameters like your access key.
AWS_S3_CUSTOM_DOMAIN = AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com'

# static media settings
STATIC_URL = 'https://' + AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com/'
MEDIA_URL = STATIC_URL + 'media/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = 'staticfiles'
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Google Maps Position
# https://pypi.python.org/pypi/django-geoposition
GEOPOSITION_GOOGLE_MAPS_API_KEY = '***'  # override with localsettings


# Analytics
GOOGLE_ANALYTICS_TRACKING_ID = 'UA-99343389-1'
FACEBOOK_PIXEL_ID = '2005046383111493'

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'


# Rest Framework

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.VerbosePageNumberPagination',
    'PAGE_SIZE': 10
}

INTERNAL_IPS = (
    '127.0.0.1',
)


CELERY_BROKER_URL = 'redis://localhost:6379/0'

DATA_TEAM_EMAIL = 'data-notifications@findwine.com'

SITE_URL = 'https://www.findwine.com'

# overridden in localsettings
RAVEN_CONFIG = {}

try:
    from .localsettings import *
except ImportError:
    # no localsettings defined
    pass

SITE = {
    'NAME': 'FindWine',
    'SUBTITLE': 'Discover wine online in South Africa',
    'DESCRIPTION': 'Search and buy hundreds of award-winning wines at your budget.',
    'KEYWORDS': 'findwine, find wine, wine, purchase wine, south african wine, wine reviews, buy wine online',
    'URL': SITE_URL,
    'IMAGE': 'wine/images/logo/logo-standard@3x.png',
    'GOOGLE_ANALYTICS_ID': GOOGLE_ANALYTICS_TRACKING_ID,
    'FACEBOOK_PIXEL_ID': FACEBOOK_PIXEL_ID,
}
