# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/award_images/')),
                ('recognition_url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['body', 'year', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='AwardBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256)),
                ('long_name', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Awardification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('1', '1/Decanter Best in Show/IWC Trophy/IWSC Trophy'), ('2', '2/Decanter Platinum/IWC Gold/Platters Wine of the year/IWSC Gold Outstanding'), ('3', '3/95-100/IWC Silver/Platters 5*/Veritas Double Gold/IWSC Gold'), ('4', '4/90-94/IWC Bronze/Platters 4.5*/Veritas Gold/IWSC Silver Outstanding'), ('5', "5/86-89/IWC Commended/Platter's 4*/Veritas Silver/IWSC Silver"), ('6', '6/83-85/Veritas Bronze/IWSC Bronze')], max_length=2)),
                ('conversion', models.CharField(blank=True, max_length=256, null=True)),
                ('normalised_rating', models.DecimalField(decimal_places=2, help_text='e.g. 10.00', max_digits=5)),
            ],
            options={
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename_1', models.CharField(max_length=256)),
                ('forename_2', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_cell', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(help_text='2 digit ISO e.g. ZA for South Africa', max_length=2)),
                ('state', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('post_code', models.CharField(max_length=16)),
                ('address_line_1', models.CharField(max_length=256)),
                ('address_line_2', models.CharField(max_length=256)),
                ('newsletter_consent', models.NullBooleanField()),
            ],
            options={
                'ordering': ['surname', 'forename_1', 'forename_2'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWineInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('1', 'Notify when wine becomes available')], max_length=2)),
                ('active_status', models.NullBooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Customer')),
            ],
            options={
                'ordering': ['customer', 'wine_vintage'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Customer')),
            ],
            options={
                'ordering': ['customer', 'wine_vintage'],
            },
        ),
        migrations.CreateModel(
            name='FoodPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Meat', 'Meat'), ('Dairy', 'Dairy'), ('Vegetable', 'Vegetable'), ('Herb or Spice', 'Herb or Spice'), ('Starch', 'Starch'), ('Sweet', 'Sweet')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alternate_names', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=2)),
                ('priority', models.PositiveIntegerField()),
                ('sales_commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Full percentage e.g. 8 for 8%', max_digits=5, null=True)),
                ('cost_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(choices=[('ZAR', 'South Africa'), ('AUD', 'Australia'), ('GBP', 'United Kingdom'), ('USD', 'United States')], max_length=3)),
                ('merchant_type', models.CharField(choices=[('1', 'CPS or Commission on sale'), ('2', 'CPC or Cost Per Click'), ('3', 'Combo or CPS and CPC')], max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/merchant_logos/')),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='MerchantWine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=2)),
                ('currency', models.CharField(choices=[('ZAR', 'South Africa'), ('AUD', 'Australia'), ('GBP', 'United Kingdom'), ('USD', 'United States')], max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 150.00', max_digits=8, null=True)),
                ('url', models.URLField(max_length=256)),
                ('external_id', models.CharField(blank=True, max_length=256, null=True)),
                ('available', models.NullBooleanField()),
                ('purchase_unit', models.CharField(choices=[('750', 'Bottle 750ml'), ('187', 'Split 187ml'), ('375', 'Half-Bottle 375ml'), ('1500', 'Magnum 1.5 litres'), ('3000', 'Jeroboam or Double Magnum 3 litres'), ('4500', 'Rehoboam 4.5 litres'), ('6000', 'Imperial or Methuselah 6 litres'), ('9000', 'Salmanazar 9 litres'), ('12000', 'Balthazar 12 litres'), ('15000', 'Nebuchadnezzar 15 litres')], max_length=5)),
                ('minimum_purchase_unit', models.PositiveIntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Merchant')),
            ],
            options={
                'ordering': ['wine_vintage', 'merchant'],
            },
        ),
        migrations.CreateModel(
            name='MerchantWineClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_timestamp', models.DateTimeField()),
                ('fulfilled_timestamp', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Customer')),
                ('merchant_wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.MerchantWine')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('US', 'United States'), ('AR', 'Argentina'), ('CL', 'Chile')], max_length=2)),
                ('geographical_unit', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('district', models.CharField(blank=True, max_length=256, null=True)),
                ('ward', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(max_length=256)),
                ('coordinates_text', models.CharField(blank=True, max_length=256, null=True)),
                ('coordinates_google', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('opening_hours_mon', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_tue', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_wed', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_thu', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_fri', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_sat', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_sun', models.CharField(blank=True, max_length=256, null=True)),
                ('opening_hours_holidays', models.CharField(blank=True, max_length=256, null=True)),
                ('closed_days', models.CharField(blank=True, max_length=256, null=True)),
                ('telephone_tasting', models.CharField(blank=True, max_length=64, null=True)),
                ('email_tasting', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('tasting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tasting_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/producer_logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ManyToManyField(to='wine.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256)),
                ('long_name', models.CharField(max_length=512)),
                ('wine_range', models.CharField(blank=True, max_length=256, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Producer')),
            ],
            options={
                'ordering': ['producer', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='WineAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_url', models.URLField(blank=True, max_length=256, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Award')),
            ],
            options={
                'ordering': ['wine_vintage', 'award'],
            },
        ),
        migrations.CreateModel(
            name='WineFoodPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(blank=True, choices=[('1', 'Perfect'), ('2', 'Ok')], max_length=2)),
                ('food_pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.FoodPairing')),
            ],
            options={
                'ordering': ['wine_vintage', 'food_pairing'],
            },
        ),
        migrations.CreateModel(
            name='WineGrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Percentage value eg. '69.0' for 69%", max_digits=5, null=True)),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Grape')),
            ],
            options={
                'ordering': ['wine_vintage', 'grape'],
            },
        ),
        migrations.CreateModel(
            name='WineVintage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('sweetness', models.CharField(blank=True, choices=[('Bone Dry', 'Bone Dry'), ('Dry', 'Dry'), ('Semi-Sweet', 'Semi-Sweet'), ('Sweet', 'Sweet'), ('Very Sweet', 'Very Sweet')], max_length=20, null=True)),
                ('wooded', models.NullBooleanField()),
                ('organic', models.NullBooleanField()),
                ('contains_sulphites', models.NullBooleanField()),
                ('vegetarian', models.NullBooleanField()),
                ('wine_of_origin', models.CharField(blank=True, max_length=256, null=True)),
                ('winemaker', models.CharField(blank=True, max_length=256, null=True)),
                ('optimal_year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('optimal_year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('alcohol_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('residual_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_acidity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_sulphur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image_pack_shot', models.ImageField(blank=True, null=True, upload_to='images/winevintage_packshots/')),
                ('tasting_notes', models.FileField(blank=True, null=True, upload_to='documents/tasting_notes/')),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Blend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.SubCategory')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Wine')),
            ],
            options={
                'ordering': ['wine', 'year'],
            },
        ),
        migrations.AddField(
            model_name='winegrape',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='winefoodpairing',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='wineaward',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='merchantwine',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='customerwinerating',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='customerwineinterest',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='blend',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Category'),
        ),
        migrations.AddField(
            model_name='award',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.AwardBody'),
        ),
        migrations.AddField(
            model_name='award',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Awardification'),
        ),
    ]
