# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpairing',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Dairy', 'Dairy'), ('Vegetable', 'Vegetable'), ('Herb or Spice', 'Herb or Spice'), ('Starch', 'Starch'), ('Sweet', 'Sweet')], max_length=64),
        ),
    ]
