# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20170619_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('US', 'United States'), ('AR', 'Argentina'), ('CL', 'Chile')], max_length=2)),
                ('level1', models.CharField(blank=True, max_length=256, null=True)),
                ('level2', models.CharField(blank=True, max_length=256, null=True)),
                ('level3', models.CharField(blank=True, max_length=256, null=True)),
                ('level4', models.CharField(blank=True, max_length=256, null=True)),
                ('level5', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winemaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename_1', models.CharField(max_length=256)),
                ('forename_2', models.CharField(blank=True, max_length=256)),
                ('surname', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.RemoveField(
            model_name='producer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='geographical_unit',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='winevintage',
            name='wine_of_origin',
        ),
        migrations.RemoveField(
            model_name='winevintage',
            name='winemaker',
        ),
        migrations.AddField(
            model_name='merchant',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='image_label_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to='images/winevintage_label_horizontal/'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='image_label_vertical',
            field=models.ImageField(blank=True, null=True, upload_to='images/winevintage_label_vertical/'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='temp_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='temp_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='appellation_primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Appellation'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='appellation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Appellation'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='wine_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Winemaker'),
        ),
    ]
