# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_auto_20170619_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='appellation_primary',
        ),
    ]
