# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_remove_producer_appellation_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winevintage',
            old_name='wine_maker',
            new_name='winemaker',
        ),
        migrations.RemoveField(
            model_name='winevintage',
            name='appellation',
        ),
    ]
