# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0007_auto_20170619_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appellation',
            options={'ordering': ['name']},
        ),
    ]
