# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0008_auto_20170620_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winevintage',
            name='appellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Appellation'),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='winemaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Winemaker'),
        ),
    ]
