# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0009_auto_20170620_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='winevintage',
            name='status',
            field=models.CharField(choices=[('Incomplete_Unavailable', 'Incomplete and Unavailable'), ('Incomplete_Available', 'Incomplete but Available'), ('Complete_Unavailable', 'Complete but Unavailable'), ('Complete_Available', 'Complete and Available'), ('Approved', 'Approved')], default='Incomplete_Unavailable', max_length=30),
        ),
    ]
