# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:35
from __future__ import unicode_literals

from django.db import migrations


def make_many_winemakers(apps, schema_editor):
    """
    Adds the Winemaker object in WineVintage.winemaker to the
    many-to-many relationship in WineVintage.winemakers
    """
    WineVintage = apps.get_model('wine', 'WineVintage')

    for wine_vintage in WineVintage.objects.all():
        if wine_vintage.winemaker:
            wine_vintage.winemakers.add(wine_vintage.winemaker)


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0011_auto_20170906_1141'),
    ]

    operations = [
        migrations.RunPython(make_many_winemakers)
    ]
