# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0012_migrate_winemaker_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winevintage',
            name='winemaker',
        ),
    ]
