# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0013_remove_winevintage_winemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='winevintage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
