# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0015_check_gps_before_deletion_20170908_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winemaker',
            options={'ordering': ['surname', 'forename_1', 'forename_2']},
        ),
        migrations.RemoveField(
            model_name='producer',
            name='coordinates_text',
        ),
        migrations.AlterField(
            model_name='appellation',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('GB', 'United Kingdom'), ('US', 'United States'), ('AR', 'Argentina'), ('CL', 'Chile')], default='ZA', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='ZA', help_text='2 digit ISO e.g. ZA for South Africa', max_length=2),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States')], default='ZA', max_length=2),
        ),
        migrations.AlterField(
            model_name='merchantwine',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States')], default='ZA', max_length=2),
        ),
        migrations.AlterField(
            model_name='merchantwine',
            name='currency',
            field=models.CharField(choices=[('ZAR', 'South Africa'), ('AUD', 'Australia'), ('GBP', 'United Kingdom'), ('USD', 'United States')], default='ZAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='merchantwineclick',
            name='currency',
            field=models.CharField(blank=True, default='ZAR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('GB', 'United Kingdom'), ('US', 'United States'), ('AR', 'Argentina'), ('CL', 'Chile')], default='ZA', max_length=2),
        ),
        migrations.AlterField(
            model_name='producer',
            name='tasting_currency',
            field=models.CharField(blank=True, choices=[('ZAR', 'South Africa'), ('AUD', 'Australia'), ('GBP', 'United Kingdom'), ('USD', 'United States')], max_length=3, null=True),
        ),
    ]
