# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0017_remove_wine_long_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['producer', 'name']},
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='short_name',
            new_name='name',
        ),
    ]
