# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0018_auto_20170911_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='winevintage',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
