# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 11:34
from __future__ import unicode_literals

from django.db import migrations
from wine.util import generate_unique_slug


def add_slugs(apps, schema_editor):
    """
    Adds slug fields to all the existing WineVintages
    """
    WineVintage = apps.get_model('wine', 'WineVintage')
    for wine_vintage in WineVintage.objects.all():
        if not wine_vintage.slug:
            # have to do this explicitly since overridden saves don't work in migrations
            # see: https://docs.djangoproject.com/en/1.8/topics/migrations/#historical-models
            wine_vintage.slug = generate_unique_slug(wine_vintage)
            wine_vintage.save()
        assert wine_vintage.slug


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0019_winevintage_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs)
    ]
