# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0022_auto_20170912_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='delivery_fees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
