# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0023_merchant_delivery_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/producer_images/'),
        ),
        migrations.AlterField(
            model_name='awardification',
            name='tier',
            field=models.CharField(choices=[('1', '1/100/Decanter Best in Show/IWC Trophy/Platters Wine of year'), ('2', '2/98-99/Decanter Platinum/IWC Gold/Platters 5*/IWSC Trophy'), ('3', '3/95-97/Decanter Gold/IWC Silver/IWSC Gold Outstanding'), ('4', '4/90-94/Decanter Silver/IWC Bronze/Platters 4.5*/IWSC Gold/Veritas Double Gold'), ('5', "5/86-89/Decanter Bronze/IWC Commended/Platter's 4*/IWSC Silver Outstanding/Veritas Gold"), ('6', "6/83-85/Decanter Seal of approval/Platter's 3.5*/IWSC Silver/Veritas Silver"), ('7', "7/80-82/Platter's 3*"), ('8', "8/76-79/Platter's 2.5*/IWSC Bronze/Veritas Bronze"), ('9', "9/73-75/Platter's 2*"), ('10', '10/70-72'), ('11', '11/50-69')], max_length=2),
        ),
    ]
