# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0024_auto_20171025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/award_images/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/merchant_logos/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/producer_images/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/producer_logos/'),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='image_label_horizontal',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/winevintage_label_horizontal/'),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='image_label_vertical',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/winevintage_label_vertical/'),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='image_pack_shot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/winevintage_packshots/'),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='tasting_notes',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documents/tasting_notes/'),
        ),
    ]
