# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0025_auto_20171031_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.CharField(editable=False, max_length=191, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='wine',
            unique_together=set([('producer', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='winevintage',
            unique_together=set([('wine', 'year')]),
        ),
    ]
