# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0027_add_slugs_to_producer_20171109_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='slug',
            field=models.CharField(editable=False, max_length=191, unique=True),
        ),
    ]
