# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0028_auto_20171109_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantwine',
            name='purchase_unit',
            field=models.CharField(choices=[('750', 'Bottle 750ml'), ('187', 'Split 187ml'), ('375', 'Half-Bottle 375ml'), ('500', 'Bottle 500ml'), ('1500', 'Magnum 1.5 litres'), ('3000', 'Jeroboam or Double Magnum 3 litres'), ('4500', 'Rehoboam 4.5 litres'), ('6000', 'Imperial or Methuselah 6 litres'), ('9000', 'Salmanazar 9 litres'), ('12000', 'Balthazar 12 litres'), ('15000', 'Nebuchadnezzar 15 litres')], max_length=5),
        ),
    ]
