# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0029_auto_20171120_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwine',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
