# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-04 12:30
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0031_merchant_affiliate_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='affiliate_params',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
