# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0033_auto_20180905_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwine',
            name='last_modified_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wine',
            name='last_modified_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='last_modified_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
