# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0034_auto_20180905_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_label_vertical',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/wine_label_vertical/'),
        ),
        migrations.AddField(
            model_name='wine',
            name='image_pack_shot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/wine_packshots/'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='When the wine was released', null=True),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='vintage_type',
            field=models.CharField(choices=[('Vintage', 'Vintage'), ('NV', 'NV')], default='Vintage', max_length=20),
        ),
        migrations.AlterField(
            model_name='winevintage',
            name='year',
            field=models.PositiveIntegerField(help_text='This is the vintage i.e. when harvest took place'),
        ),
    ]
