# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-07 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0035_auto_20190607_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winevintage',
            name='image_label_horizontal',
        ),
    ]
