# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wine.models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0038_auto_20190718_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename_1', models.CharField(max_length=256)),
                ('forename_2', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(max_length=256)),
                ('initials', models.CharField(max_length=3)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['surname', 'forename_1', 'forename_2'],
            },
        ),
        migrations.CreateModel(
            name='CriticReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, max_length=191)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Critic')),
            ],
            options={
                'ordering': ['critic', 'name', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=4)),
                ('score_max', models.CharField(default='100', max_length=4)),
                ('review', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('recognition_url', models.URLField(blank=True, max_length=256, null=True)),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Critic')),
            ],
            options={
                'ordering': ['wine_vintage', 'critic'],
            },
        ),
        migrations.CreateModel(
            name='Viticulturist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename_1', models.CharField(max_length=256)),
                ('forename_2', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(max_length=256)),
                ('facebook', models.URLField(blank=True, max_length=256, null=True)),
                ('twitter', models.URLField(blank=True, max_length=256, null=True)),
                ('instagram', models.URLField(blank=True, max_length=256, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['surname', 'forename_1', 'forename_2'],
            },
        ),
        migrations.AddField(
            model_name='appellation',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.NullBooleanField(help_text='Yes to add a merchant that should show up in MerchantWine choices'),
        ),
        migrations.AddField(
            model_name='producer',
            name='facebook',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='instagram',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='linkedin',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='twitter',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='fact_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documents/wine_fact_sheets/'),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='facebook',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='instagram',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='linkedin',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='twitter',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='biodynamic',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='vegan',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='volatile_acidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='merchantwine',
            name='country_model',
            field=models.ForeignKey(blank=True, default=wine.models.Country.get_default, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Country'),
        ),
        migrations.AlterField(
            model_name='merchantwine',
            name='purchase_unit',
            field=models.CharField(choices=[('750', 'Bottle 750ml'), ('187', 'Split 187ml'), ('375', 'Half-Bottle 375ml'), ('500', 'Bottle 500ml'), ('1000', 'Growler 1 litre'), ('1500', 'Magnum 1.5 litres'), ('3000', 'Jeroboam or Double Magnum 3 litres'), ('4500', 'Rehoboam 4.5 litres'), ('5000', '5 litres'), ('6000', 'Imperial or Methuselah 6 litres'), ('9000', 'Salmanazar 9 litres'), ('12000', 'Balthazar 12 litres'), ('15000', 'Nebuchadnezzar 15 litres')], max_length=5),
        ),
        migrations.AlterField(
            model_name='producer',
            name='tasting_currency',
            field=models.CharField(blank=True, choices=[('ZAR', 'South Africa'), ('AUD', 'Australia'), ('GBP', 'United Kingdom'), ('USD', 'United States')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='forename_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='criticreview',
            name='wine_vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineVintage'),
        ),
        migrations.AddField(
            model_name='winevintage',
            name='viticulturists',
            field=models.ManyToManyField(blank=True, related_name='viticulturists', to='wine.Viticulturist'),
        ),
        migrations.AlterUniqueTogether(
            name='criticreport',
            unique_together=set([('critic', 'name', 'year')]),
        ),
    ]
