# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0038_auto_20190717_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
