# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wine', '0034_auto_20180905_1352'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clickthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('merchant_wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.MerchantWine')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
